apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-url-shortener
  labels:
    app: springboot-url-shortener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-url-shortener
  template:
    metadata:
      labels:
        app: springboot-url-shortener
    spec:
      containers:
        - name: springboot-url-shortener
          image: ousmane1999/ultimate-cicd:replaceImageTag
          ports:
            - containerPort: 8089
