apiVersion: v1
kind: Service
metadata:
  name: springboot-url-shortener
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8089
      protocol: TCP
  selector:
    app: springboot-url-shortener